version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - ${APP_PORT}:80
    container_name: ${APP_NAME}_nginx
    depends_on:
      - app
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www:rw
    container_name: ${APP_NAME}_php
    depends_on:
      - db
    networks:
      - app
    user: "1000:1000"

  db:
    image: mysql:latest
    volumes:
        - 'mysql:/var/lib/mysql'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${APP_NAME}_database'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    container_name: ${APP_NAME}_db
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql:
    driver: local